### PR TITLE
Use snake_case for naming Python files

### PR DESCRIPTION
**Pull request by dkmiller**
Closes https://github.com/github/copilot-codespaces-demo/issues/12.

### CODE REVIEW

**Comment by dkmiller** [comment]
@joshaber &mdash; can you take a look?

**Comment by joshaber** [comment]
Thanks @dkmiller! Mind updating the code tour too? https://github.com/github/copilot-codespaces-demo/blob/68a6c40f949fa8f11a7d2a4054496ae5780d7951/.tours/JSONtoUser.tour

**Comment by dkmiller** [comment]
@joshaber done! Take another look?

**Review by joshaber — APPROVED** [review]
Looks great, thank you! ⚡

**Pull request merged**
